version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17
  build:
    commands:
      - echo "Building the project..."
      - mvn clean install
artifacts:
  files:
    - target/*.jar
